
name: Integration tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lemmoi/transition_sampling:cp2k_plumed

    steps:
    - name: CP2K Test
      shell: bash
      run: |
        source /src/plumed/sourceme.sh
        /src/cp2k.ssmp
