
name: Integration tests

on:
  push:
    branches: [ main ]

jobs:
  cp2k:
    runs-on: ubuntu-latest
    container: lemmoi/transition_sampling:cp2k_gro_plumed

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      shell: bash
      run: |
        pip3 install pytest
        pip3 install -r requirements.txt
        pip3 install .

    - name: Integration Tests
      shell: bash
      run: |
        source /src/plumed/sourceme.sh        
        pytest transition_sampling/tests/integration_tests/
